<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>ARTR.Pien.UnitTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ARTR.Pien.Core\ARTR.Pien.Core.csproj" />
    <ProjectReference Include="..\..\src\ARTR.Pien.Web\ARTR.Pien.Web.csproj" />
    <ProjectReference Include="..\..\src\ARTR.Pien.Checks\ARTR.Pien.Checks.csproj" />
    <ProjectReference Include="..\..\src\ARTR.Pien.Engine\ARTR.Pien.Engine.csproj" />
    <ProjectReference Include="..\..\src\ARTR.Pien.Reporting\ARTR.Pien.Reporting.csproj" />
    <ProjectReference Include="..\..\src\ARTR.Pien.Storage\ARTR.Pien.Storage.csproj" />
    <ProjectReference Include="..\ARTR.Pien.Testing\ARTR.Pien.Testing.csproj" />
  </ItemGroup>

</Project>
