<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\src\ARTR.Pien.Core\ARTR.Pien.Core.csproj" />
    <ProjectReference Include="..\..\src\ARTR.Pien.Web\ARTR.Pien.Web.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
