<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>ARTR.Pien.FunctionalTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ARTR.Pien.Cli\ARTR.Pien.Cli.csproj" />
    <ProjectReference Include="..\..\samples\ARTR.Pien.SampleSite\ARTR.Pien.SampleSite.csproj" />
    <ProjectReference Include="..\..\samples\ARTR.Pien.SampleApi\ARTR.Pien.SampleApi.csproj" />
    <ProjectReference Include="..\ARTR.Pien.Testing\ARTR.Pien.Testing.csproj" />
  </ItemGroup>

</Project>
