<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <AssemblyName>ARTR.Pien.Cli</AssemblyName>
    <RootNamespace>ARTR.Pien.Cli</RootNamespace>
    <Description>ARTR Pien command-line interface.</Description>
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>pien</ToolCommandName>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ARTR.Pien.FunctionalTests" />
    <InternalsVisibleTo Include="ARTR.Pien.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ARTR.Pien.Hosting\ARTR.Pien.Hosting.csproj" />
  </ItemGroup>

</Project>
